import { mkdir, readFile, writeFile, rm } from "node:fs/promises";
import path from "node:path";
import type { PhotoStorage } from "./photo-storage";

// turbopackIgnore: root is a runtime-configured path (env var), not a
// static project file — without this hint Turbopack's file tracer follows
// the resolve() call and traces the entire project unintentionally.
const ROOT = path.resolve(/*turbopackIgnore: true*/ process.env.PHOTO_STORAGE_ROOT || "./.data/event-photos");

// Guards against a key like "../../etc/passwd" escaping ROOT — keys are always
// generated by our own code (eventId/photoId/name), never taken verbatim from
// user input, but this keeps the class safe even if that assumption ever slips.
function resolveKey(key: string): string {
  const resolved = path.resolve(ROOT, key);
  if (resolved !== ROOT && !resolved.startsWith(ROOT + path.sep)) {
    throw new Error(`Refusing to resolve photo storage key outside root: ${key}`);
  }
  return resolved;
}

export class LocalPhotoStorage implements PhotoStorage {
  async save(key: string, data: Buffer): Promise<void> {
    const filePath = resolveKey(key);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, data);
  }

  async read(key: string): Promise<Buffer> {
    return readFile(resolveKey(key));
  }

  async delete(key: string): Promise<void> {
    await rm(resolveKey(key), { force: true });
  }

  async deleteAllForEvent(eventId: string): Promise<void> {
    const eventDir = resolveKey(eventId);
    await rm(eventDir, { recursive: true, force: true });
  }
}
